# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-slim-bookworm

# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Set working directory
WORKDIR /app

# Copy the project files
COPY . .

# Install the project and its dependencies
RUN uv sync --frozen --no-dev

# Set the command to run the MCP server
ENTRYPOINT ["uv", "run", "bcci-tv-mcp"]
